# Generated by Django 5.2.15 on 2026-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('LESSON', 'New Lesson'), ('QA', 'Q&A Activity'), ('REFUND', 'Refund Event'), ('ANNOUNCEMENT', 'Announcement')], default='ANNOUNCEMENT', max_length=20)),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
